### ISSUE TITLE
Phase 3: Graphics/interface

### ISSUE THREAD

**Issue by hp1932** [hp1932/cis510GameProject#11]
- Create graphics for supply-purchasing phase
- Hook up graphics in Unity

**Comment by bilbaeno** [comment]
I have started laying this out with the assets we have.

I'll need to know the different number of ingredients we are going to have included in the Alpha build to finish this.

**Comment by hp1932** [comment]
Right now I have the code set up for the following ingredients:
- Bread
- Condiments
- Cheese
- Ham
- Turkey
- Veggie Patty

**Comment by chapman3** [comment]
I think we decided on Thursday that for alpha we should be concerned only with Bread, Ham, Turkey, Veggie Patty. Cheese and Condiments are conditional further than primary protein choice, and can wait for Beta.

**Comment by hp1932** [comment]
This is done, I believe. Reopen if I am wrong...
