### ISSUE TITLE
Phase 2: Change graph to use real data from global object

### ISSUE THREAD

**Issue by hp1932** [hp1932/cis510GameProject#16]
See RestaurantStatistics in Serializables.cs to see the persistent data being stored. You can load this data in the local scene with

`localPlayerData = GlobalControl.Instance.savedPlayerData;`

**Comment by hp1932** [comment]
Here is some quick documentation on how to get data to/from the global object.

*_Important edit: *_ In _every_ scene where you want to access global data, you need to include the "GlobalGameObject" prefab in the hierarchy. (Sorry I did not mention this earlier.)

First you will need to declare a local copy of the object. You can do this at the top of the class:
`RestaurantStatistics localPlayerData;`

Then in Start() or Awake() you can get a store a copy of the global instance in it.
`localPlayerData = GlobalControl.Instance.savedPlayerData;`

Anywhere in the class you can now access any of the variables in the RestaurantStatistics class with localPlayerData using the dot operator. 
For example:
`localPlayerData.currentBalance;`

You can freely alter localPlayerData without it affecting the global instance as long as you don't assign to the global instance again. When you are ready to save back to the global instance, though,  you can do so like this:
`GlobalControl.Instance.savedPlayerData = localPlayerData;`

This will overwrite what is saved globally, so make sure you only do this operation once all the variables you want to change are set and nothing is erroneously or unintentionally changed.

**Comment by chapman3** [comment]
Great documentation here. Sol, let me know if you need any assistance with this and I can try to help.

**Comment by solcjoye** [comment]
Hannah - This is fantastic, thank you. I am working on this now, and into tonight. I'll respond back here if I have any issues (likely).

**Comment by solcjoye** [comment]
OK guys, sorry... have to ask for help as I am getting stuck on this. I created a short script (didnt want to add to existing) to the draw scene... When I test in monodevelop it comes up w no problems, but when I try and run it, it basically halts the movement of the demand line, and comes up with an error:

"Null Reference Exception: Object reference not set to an instance of an object"

This is what I have so far from Hannah's instructions above:

**using UnityEngine;
using System.Collections;

public class BringGlobalVariable : MonoBehaviour {

```
public RestaurantStatistics localPlayerData;

void Start () {

    localPlayerData = GlobalControl.Instance.savedPlayerData;
    print(localPlayerData.dishPrices);
            // Above is just so I can see what is IN the dishPrices

}
void Update () {

}
```

}**

Also, I am having an odd issue with the rendering of the horizontal and vertical lines when they are being drawn... In the game view they dont quite reach the point where they should be colliding with the walls (which will be hidden, I just left them visible for now to test) - 

See here: https://youtu.be/l84FqCaXjIQ

Sorry to ask for what I am sure are simple answers... I just think I am wasting more time spinning wheels than anything else at this point...

Thx,

-S.

**Comment by hp1932** [comment]
Oh yeah, runtime errors are a pain to debug! Do you know which object you are getting the null reference on? It usually says at the bottom part of the error. Otherwise, you can double-click the error and it should bring you to the relevant line of code in MonoDevelop.

**Comment by hp1932** [comment]
This is done, I believe. Reopen if I am wrong...
