### ISSUE TITLE
Phase 1: everyone is sad

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#18]
[video link](https://youtu.be/r-eHEYd9--Y)

**Comment by bilbaeno** [comment]
Not actually an issue. I was just testing customer faces and thought I should share the sadness.
- [x] nothing

**Comment by hp1932** [comment]
Haha, nice! It's looking good.

(I'll admit the title of this ticket scared me for a minute. I thought there was some horrible bug or something that would make us all sad. xD)
