### ISSUE TITLE
Git Help Article

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#24]
If you want some quick (very quick) reading on how Git works, check out this page: http://rogerdudler.github.io/git-guide/

It's mostly graphic and brushes over checkout, pull, push, merge, etc.

Also,
![](https://imgs.xkcd.com/comics/git.png)

**Comment by chapman3** [comment]
The funny part about that picture is THATS EXACTLY WHAT I DO. I have a seperate copy of my economy branch saved locally because I was afraid it would obliterate itself when I pushed it last night.
