### ISSUE TITLE
Changing to from a horizontal to a vertical aspect ratio?

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#28]
Hey guys,

Does anyone have any objections to switching from a horizontal to a vertical aspect ratio? (From 16:9 to 9:16)

My main motivation for this is the UI layout. I've been struggling to fit what we have into a horizontal layout. Most of the UI elements we have currently scale veritcally (the purchase screen for example) which lends itself well to a narrow and tall screen. The pixel elements also tend to look better the larger they are, and a narrower width would allow me to bump that up.

Just something I've been thinking about going forward, let me know your thoughts. Most of the work for this would be on me, which I am okay with.

**Comment by solcjoye** [comment]
That’d be great for me as well I think…

Sol Joye
Online Instructional Design Coordinator
Global and Online Education
University of Oregon
Email: scj@uoregon.edumailto:scj@uoregon.edu
Skype: Solcjoye

On May 13, 2016, at 12:09 PM, bilbaeno <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey guys,

Does anyone have any objections to switching from a horizontal to a vertical aspect ratio?

My main motivation for this is the UI layout. I've been struggling to fit what we have into a horizontal layout. Most of the UI elements we have currently scale veritcally (the purchase screen for example) which lends itself well to a narrow and tall screen. The pixel elements also tend to look better the larger they are, and a narrower width would allow me to bump that up.

Just something I've been thinking about going forward, let me know your thoughts. Most of the work for this would be on me, which I am okay with.

**Comment by hp1932** [comment]
That's fine with me, especially if it fixes some of the UI issues.

**Comment by bilbaeno** [comment]
From here on out it seems like most of my job will be making things look nice (other than implementing those phase 1 items I missed), so the change of screen size shouldn't make for too much extra work.

I'll start planning for that, thanks for the feedback.

**Comment by bilbaeno** [comment]
![screenshot_eatcon](https://cloud.githubusercontent.com/assets/7476120/15263185/8a739324-191c-11e6-8b10-8dd1d92a7fc1.png)

Hey Sol, this is what I had in mind for the layout. Will that work for your graph?

**Comment by solcjoye** [comment]
Looks fantastic - well done.

Sol Joye
Instructional Design Coordinator
Global and Online Ed
University of Oregon

----- Reply message -----

**Comment by chapman3** [comment]
Looks like the starts to a mobile game pivot... with just the right amount of room at the bottom for an ad banner... hmmm hah

Looks great, especially the file type tabs at the top, can click between the scenes like that I assume.

**Comment by bilbaeno** [comment]
> Looks great, especially the file type tabs at the top, can click between the scenes like that I assume.

Well since the player isn't always in control of scene transitions, it was more to show where in the game the player currently is. Sort of like web breadcrumbs.

EDIT: aaaand I just realized we have 4 scenes, not 3.

**Comment by chapman3** [comment]
Oh that makes sense, I was thinking of it more like each tab with a different title:
"reports"
"purchasing"
"set prices"
etc.. 
Then like a button somewhere to proceed to the next days simulation.

But either is a viable route

**Comment by bilbaeno** [comment]
![screenshot_eatcon](https://cloud.githubusercontent.com/assets/7476120/15264741/bd2b9316-192b-11e6-8c8c-a9c5e00083f9.png)

Here's a draft with 4 color coded tabs. (The center space is left blank to account for the differing scenes.)

Planning to create icons for them as follows:
Simulation = a building
Report = piece of paper
Pricing = graph line
Inventory = money sign

**Comment by hp1932** [comment]
Looks fancy! My only concern would be if the simulation be large enough for the player to see the customer feedback and everything else going on?
