### ISSUE TITLE
Customer Order Logic

### ISSUE THREAD

**Issue by hp1932** [hp1932/cis510GameProject#3]
- [x] Set up logic to have each customer have an order, based on the demand curve
- [ ] Display order in speech bubble above customer (May be an Art Designer task.)
- [x] Logic for fulfilling orders (removing ingredients from storage, obtaining money, etc)
- [x] Error case when there are not enough ingredients.
- [ ] Graphic/visual cue for user to see customer left without being served. (Art Designer Task)

This setup process should be local to phase 1 of the game, but be informed by global economy data.

**Comment by bilbaeno** [comment]
Here's a couple things I'll need to know when designing the visuals:
- [ ] Total number of different ingredients the player can purchase
- [ ] Scale of ingredients (quantity) needed to be represented visually (ie. how much of each ingredient we can expect the player to have at any given time)

No rush, this only effects the storage room in Phase 1.

**Comment by hp1932** [comment]
Ok. This is porbably be a Level Designer task, but I can think about it as well.

**Comment by solcjoye** [comment]
For now, lets keep it simple... so lets do a subway-esque sandwich shop. We can always change / update ingredients to complicate thing later... For now, for Friday, lets keep it VERY simple and have the following ingredients:
- Bread
- Turkey
- Ham
- Condiments
- Veggie sandwich
- Cheese

I think the player should be able to buy up to 100 of each of those, with a potential of 50 - 100 customers a day to start with. Visual representation of the ingredients would maybe be most easily understood by just keeping them as actual digits versus trying to visually show or represent the number of items in sprites, etc.

Thoughts?

**Comment by bilbaeno** [comment]
> Visual representation of the ingredients would maybe be most easily understood by just keeping them as actual digits versus trying to visually show or represent the number of items in sprites, etc.

Agreed. I was planning to have the store house as an additional visual to give the player an idea of something happening inside the restaurant. Numbers will be included in the UI as well.

**Comment by solcjoye** [comment]
For sure... and thinking about this, while watching a tutorial on some line drawing functions... are we doing this in 2D or 3D? I think the current graphic assets could go either way for the store etc?

**Comment by bilbaeno** [comment]
I believe it would be best to go with the 2D default project setup for this. All of the assets we have currently are 2D, including the UI.

**Comment by hp1932** [comment]
Yes, the project I currently have in git is 2D.

**Comment by solcjoye** [comment]
OK - Yeah, I think this is best for sure, BUT... the demand curve line drawing code I am using is the LineRenderer command... Which, as I understand it, ONLY works in 3d mode, not 2d... and I've tried a couple of other line drawing tools in 2d with not much luck thus far... I'll keep playing with it, but if you guys have any good thoughts on how to draw out lines in realtime, not just the start of a scene - let me know...

-S.

**Comment by solcjoye** [comment]
OK - Have LineRenderer working for 2D - It is slow going for me :)

**Comment by hp1932** [comment]
Based on the ingredients given, I am assuming these would be the dishes/recipes offered?
- Ham Sandwich (Bread, ham, condiments, cheese)
- Turkey Sandwich (Bread, turkey, condiments, cheese)
- Veggie Sandwich (Bread, veggie patty, condiments, cheese)

Is that right? I am working on coding up the order logic now and want to make sure I am understanding the recipes correctly.

Also, how do we want to handle the case where the customer orders something and we don't have all the ingredients? Should we check all ingredients before making it, then if ANY are missing, we don't accept any money and the customer does not get food?

**Comment by hp1932** [comment]
One thing I am brainstorming right now is how to assign customers their orders based on the demands. I considered storing the demands as a list of priorities, then assign each customer an order based on those probabilities. Can you think of any issues with that idea? Any better ones?

I still need to do the logic for adapting the demands after each level, too. This whole demand curve thing is what I am stuck on currently. It might just be not enough blood flowing to my brain, though. Haha.
