### ISSUE TITLE
Refactor Scene names in Project & Scripts

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#35]
This is pretty minor, but I think it's some good clean-up to do for the Beta build.
### Current:
- Demand Draw
- phase1
- phase2
- phase3
### Refactor to: (not including parentheses)
- phase1 (simulation)
- phase2 (report)
- phase2b (graph/pricing)
- phase2c (purchasing)

This will need to be changed in both the Unity project view, and all associated scripts.

Any objections/changes to the naming?
Anyone know all the script locations that need to be modified?

**Comment by hp1932** [comment]
This might be more trouble than it is worth, but if you still want to update the names, here are the locations I know of that would need to be changed. There may be more somewhere
- GlobalControl.cs - in function Update() line 49
- ButtonController.cs - in function SwitchToSimulation() line 45
- MoveWith.cs - in function finalSubmit() line 343
- MenuController.cs - in Restart() line 16

In Unity Project:
- phase2.unity scene - Canvas -> Buttons -> GoToGraphButton the onClick parameter needs to be updated
- phase2.unity scene - Canvas -> Buttons -> PurchaseButton the onClick parameter needs to be updated
- phase3.unity scene - Canvas -> Buttons -> ReturnToReport the onClick parameter needs to be updated

**Comment by bilbaeno** [comment]
Thanks! I'll get to it at some point. It's been bugging me...I'm a bit neurotic about refactoring.

**Comment by hp1932** [comment]
Well, I hope you don't take a good look at a lot of my code, then. Haha. Not my best work, to be sure.

**Comment by bilbaeno** [comment]
Don't worry, I think we're all in the same boat in that regard.
