### ISSUE TITLE
BUG: Money Values Ending in .X999999 

### ISSUE THREAD

**Issue by chapman3** [hp1932/cis510GameProject#51]
After sometimes only on play through the UI displays money on hand and earned past the 2nd decimal place, something like 61.79999999 for example. Probably a bug with how on hand money is calculated, perhaps related to the recent addition of soda?

**Comment by chapman3** [comment]
Fixed on report screen, but not purchasing

**Comment by hp1932** [comment]
Fixed with e4fbd7c753a5752693ee303b1dd2656b278611dd and e1fc8baf0651eb870d701773a65f20629589ed6d
