### ISSUE TITLE
Syncing w Git branch

### ISSUE THREAD

**Issue by solcjoye** [hp1932/cis510GameProject#6]
Hey guys, my lack of Git experience showing here...

I have some work done, I want to add to a branch so we can start to figure out how to incorporate together etc. I have the Git desktop installed, but I am not sure how to connect it to THIS repository versus it just creating a new one, and I can also create a branch and upload my current work folders into it, but A. it told me I need to do it in chunks of less than 100 files at a time, and B. I am not sure that is the best / correct method? Does that mean I'll manually upload whenever I want to push out new work / updates?

Thanks,

-S.

**Comment by ryeleo** [comment]
General workflow might be:
1. "Clone" a version of this repository
    git clone https://...
2. "Checkout" a new branch where you will be making changes
    git checkout -b feature_x
3. "Commit" often while you are working! 
    git add -A
    git commit -m "Added sprites!" 
4. "Push" your branch back to origin
    git push origin feature_x
5. Make a "Pull Request" on Github
   This is done using the github UI
6. Review the pull request then "merge and delete" the branch. This will bring your 'feature_x' changes into your master branch. :D

**Comment by solcjoye** [comment]
Thx Ryan, that makes sense - I'll play around with that for a bit.

**Comment by bilbaeno** [comment]
Sol,
If you're on Windows you may want to try using SourceTree. If you're not familiar with Git it makes it pretty simple, and you can even log in with your GitHub account and select repositories to clone locally.
