### ISSUE TITLE
Implement Web Player

### ISSUE THREAD

**Issue by chapman3** [hp1932/cis510GameProject#61]
From the final build requirements document:

> 1.    [50]    Build your game for the Unity Web Player. Submit the resulting .html and .unity3d files with    your    document link. I will   host    these on the course web site indefinitely so that you can link to them, etc.

More details from Unity at: http://docs.unity3d.com/Manual/WebPlayerDeployment.html

**Comment by hp1932** [comment]
I set up Unity to run with web player and added some graphics to the html page to make it look nifty. I'm going to set it up to work with a template to make building easier (right now clicking "Build and Run" overwrites my custom html.) I've just been running into some issues with that.

**Comment by hp1932** [comment]
See commits 0f1212589b6287442817dc3942f2585a2a763c16, 72c6e7244b9a8a945b34f9fdb538c1a228d659f8, and d6b42a6f9a2a3a598901ddcd06df279d2ce901ad

(Merge commit: d1cdf2866e7653c00f3e23a9887fd290669d7e5f)
