### ISSUE TITLE
Grabbing a variable (float, int, whatever) from a parent GameObject

### ISSUE THREAD

**Issue by solcjoye** [hp1932/cis510GameProject#7]
I've looked at a few YouTube videos and tutorials, but cannot seem to successfully pull variables (specifically a public float) from a parent GameObject to a child GameObject... any thoughts would be great.

**Comment by hp1932** [comment]
I haven't needed to do this yet, but have you tried using something like
`childObject.transform.parent.gameObject`

then accessing the public members of that in the child script?

**Comment by ryeleo** [comment]
A quick test on my end shows that I can use "gameObject.GetComponentInParent<ClassName> ();" to get a handle to the parent script.

Example where this script is a component of a child object whose parent is the 'player' in the "Roll-a-ball" tutorial.

```
public class Testing : MonoBehaviour {

  private PlayerController playerController; 
  // Use this for initialization 
  void Start () {
    playerController = gameObject.GetComponentInParent<PlayerController> ();
    playerController.speed = 0.1f;
  }
}
```
